library(ggplot2)

la <- rstan::extract(fit)
d_obs <- data.frame(X=T, Y=Y)
qua <- apply(la$Y_new, 2, quantile, prob=c(0.025, 0.25, 0.5, 0.75, 0.975))
d_est <- data.frame(X=T_new, t(qua))
colnames(d_est) <- c('X', 'p2.5', 'p25', 'p50', 'p75', 'p97.5')
p <- ggplot()
p <- p + theme_bw() + theme(text=element_text(size=18))
p <- p + geom_ribbon(data=d_est, aes(x=X, y=p50, ymin=p2.5, ymax=p97.5), fill='black', alpha=0.25)
p <- p + geom_ribbon(data=d_est, aes(x=X, y=p50, ymin=p25, ymax=p75), fill='black', alpha=0.5)
p <- p + geom_line(data=d_est, aes(x=X, y=p50), color='black', size=0.4)
p <- p + geom_point(data=d_obs, aes(x=X, y=Y), color='black', alpha=0.9, size=3, shape=1)
p <- p + labs(x='T', y='Y')
p <- p + coord_cartesian(xlim=c(0, 2.5))
ggsave(file='output/fig1.png', plot=p, dpi=300, width=4, height=3)